[package]
name = "axion-net"
version = "1.0.0"
edition = "2021"

[dependencies]
axion-core = { workspace = true }
libp2p = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }